// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlRBxJvU1WmXaABNCURiN5IC_vnRtQlL4',
    appId: '1:633936751414:web:1ad6bf7398319904412197',
    messagingSenderId: '633936751414',
    projectId: 'english-app-ece16',
    authDomain: 'english-app-ece16.firebaseapp.com',
    storageBucket: 'english-app-ece16.firebasestorage.app',
    measurementId: 'G-G4NGN9YYJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCocayPv8Q7sylQzTt0Km6VHLLFjhkvegY',
    appId: '1:633936751414:android:e14e05b98375c32b412197',
    messagingSenderId: '633936751414',
    projectId: 'english-app-ece16',
    storageBucket: 'english-app-ece16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC14bFrJibjbXq1XRwwFdx2gon28qfj3FE',
    appId: '1:633936751414:ios:705854115523ea1a412197',
    messagingSenderId: '633936751414',
    projectId: 'english-app-ece16',
    storageBucket: 'english-app-ece16.firebasestorage.app',
    iosBundleId: 'com.example.gravityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC14bFrJibjbXq1XRwwFdx2gon28qfj3FE',
    appId: '1:633936751414:ios:705854115523ea1a412197',
    messagingSenderId: '633936751414',
    projectId: 'english-app-ece16',
    storageBucket: 'english-app-ece16.firebasestorage.app',
    iosBundleId: 'com.example.gravityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlRBxJvU1WmXaABNCURiN5IC_vnRtQlL4',
    appId: '1:633936751414:web:882c0fe73c66d860412197',
    messagingSenderId: '633936751414',
    projectId: 'english-app-ece16',
    authDomain: 'english-app-ece16.firebaseapp.com',
    storageBucket: 'english-app-ece16.firebasestorage.app',
    measurementId: 'G-ZNT48BBTE5',
  );
}
